# Generated by Django 3.2.6 on 2021-10-03 13:23

import App_Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Contact',
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'NewsLetter',
                'db_table': 'NewsLetter',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Project Category',
                'db_table': 'Project Category',
            },
        ),
        migrations.CreateModel(
            name='ResumeDetailsEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.TextField()),
                ('startyear', models.IntegerField()),
                ('endyear', models.IntegerField()),
                ('degreeName', models.CharField(max_length=264)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'ResumeEducationDetails',
                'db_table': 'ResumeEducationDetails',
            },
        ),
        migrations.CreateModel(
            name='ResumeExperienceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.TextField()),
                ('startyear', models.IntegerField()),
                ('endyear', models.IntegerField()),
                ('jobdesignation', models.CharField(max_length=264)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'ResumeExperienceDetails',
                'db_table': 'ResumeExperienceDetails',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=App_Main.models.upload_project)),
                ('category', models.ManyToManyField(blank=True, to='App_Main.ProjectCategory')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'db_table': 'Projects',
            },
        ),
    ]
