# Generated by Django 3.2.6 on 2021-10-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeexperiencedetails',
            name='endyear',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='resumeexperiencedetails',
            name='startyear',
            field=models.CharField(max_length=264),
        ),
    ]
